### ISSUE TITLE
Issue in Problem 2

### ISSUE THREAD

**Issue by VioletaKirova** [TheTeam-TechModuleJan2018/ProgrammingFundamentals#2]
Forgot to rename variable "b".

**Comment by PranksterGangster** [comment]
![nah](https://user-images.githubusercontent.com/37193765/37241884-224e985c-2469-11e8-9496-57d1c475417c.png)

**Comment by VioletaKirova** [comment]
Sorry <3

**Comment by PranksterGangster** [comment]
OwO






 >-------- Оригинално писмо --------

 >От: VioletaKirova notifications@github.com

 >Относно: Re: [TheTeam-TechModuleJan2018/ProgrammingFundamentals] Issue in
 Problem 2 (#2)

 >До: TheTeam-TechModuleJan2018/ProgrammingFundamentals  

 >Изпратено на: 10.03.2018 13:46



 
 
  
Sorry
